title: Data Science Roadmap
description: If you start now, you will start seeing the result one day earlier than if you wait until tomorrow ~ Unkown
show_downloads: true

baseurl: "/blog" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://davidphun.github.io" # change this to the base hostname & protocol for your site


google_analytics:

# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: David
image: /thumbnail-jumbo.png
twitter:
  username:

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['now', 'about', 'contact']

markdown: kramdown
kramdown:
   math_engine: mathjax